### ISSUE TITLE
Is this possible without cutting lanes?

### ISSUE THREAD

**Issue by chrifey** [AlejandroPerez92/cdj800spi#1]
I stumbled over this, when I was searching a minimal invasive way to retrofit my CDJ 800 MK2 with Midi, in order to build sort of Nexus Style Player based on Raspberry / Mixxx and the Pioneered Skin.

The Midi Mods I found are all invasive and will break existing functionality of the CDJs. As far as I understand this, it would be possible to implement a switch between "original" mode and the SPI "tap mode". Am I correct?

I would be very happy to help!

**Comment by AlejandroPerez92** [comment]
This project only implements a 'library' for decoding/encoding SPI messages. To enable the 'original' mode, you will need a switch with 4 lines or a board with 2 SPI interfaces to resend the SPI messages to the original board.

I plan to port the project to the ESP32S3 board, which has 2 SPI interfaces and a USB HID interface. Therefore, technically, it will be possible to implement your project with this board.

I just need to finish a few things in the messages to control the main display.

Any help is appreciated, feel free to send a pull request!

**Comment by chrifey** [comment]
Thanks very much for clarification!

Your idea with the ESP32S3 board sounds great. I think I will order two and at first try your library, then use it so implement at least midi output as a first step.

Thanks very much for your work!
