### ISSUE TITLE
Output example?

### ISSUE THREAD

**Issue by david-res** [AlejandroPerez92/cdj800spi#2]
Do you happen to have a log of outputs from the jog wheel speed, direction, position, touch sensor enabled/disabled, pitch fader etc?
I’d like to understand what range of values it outputs

**Comment by AlejandroPerez92** [comment]
I don't have any log, but you can see how the data is collected in this object
https://github.com/AlejandroPerez92/cdj800spi/blob/main/include/StatusMessage.h
https://github.com/AlejandroPerez92/cdj800spi/blob/main/src/StatusMessage.cpp
